encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: "non-empty-key"
  type: openai_chat
  model: "google/gemma-3-1b-it"
  api_base: "http://localhost:8000/v1"
  concurrent_requests: 4

embeddings:
  llm:
    api_key: "non-empty-key"
    type: openai_embedding
    model: "BAAI/bge-small-en-v1.5" # Optional, only if you also have embedding endpoints on vLLM/Ollama
    api_base: "http://localhost:8000/v1"

# We customize the path to where our custom script generated the files.
input:
  file_type: text
  base_dir: "input"

storage:
  base_dir: "output"

reporting:
  base_dir: "output/reports"

cache:
  base_dir: "output/cache"

cluster_graph:
  max_cluster_size: 10

community_reports:
  max_length: 2000
  max_input_length: 8000
